<?php

namespace app\modules\Apiv1\controllers;

//use yii\web\Controller;
use yii\rest\ActiveController;
use app\models\PacientepatologiaSearch;
use app\models\PatologiaSearch;
use app\models\Usuario;
use app\modules\Apiv1\models\Paciente;
use app\modules\Apiv1\models\PacienteSearch as ModelsPacienteSearch;
use app\modules\Apiv1\models\Patologia;
use app\modules\Apiv1\models\Pacientepatologia;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataFilter;
use yii\data\ActiveDataProvider;
use yii\data\DataFilter;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

/**
 * Default controller for the `apiv1` module
 */
class PacienteController extends ActiveController
{
    public $modelClass = 'app\modules\Apiv1\models\Paciente';

    public function beforeAction($action)
    {
<<<<<<< HEAD
        if ($action->id == 'create' || $action->id == "update") {
=======
        if ($action->id == 'create'|| $action->id == "update") {
>>>>>>> cc9bbe6fee51c4d4a8f405083d584071763be1a8
            Yii::$app->db->beginTransaction();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        if ($action->id == 'create' || $action->id == "update") {
            $params = Yii::$app->getRequest()->getBodyParams();
<<<<<<< HEAD
            if (isset($params['patologiasElegidas'])) {
                foreach ($params['patologiasElegidas'] as $pat) {
                    $model = new Pacientepatologia([
                        'paciente_id' => $params['id_paciente'],
                        'patologia_id' => $pat['id_patologia']
                    ]);
=======
            if (isset($params['patElegidas'])) {
                foreach ($params['patElegidas'] as $pat) {
                    $model = new Pacientepatologia([
                        'paciente_id' => $params['id_paciente'],
                         'patologia_id' => $pat['id_patologia']
                         ]);
>>>>>>> cc9bbe6fee51c4d4a8f405083d584071763be1a8
                    if (!$model->save()) {
                        $result->addErrors($model->getErrors());
                    }
                }
            }
            $transaction = Yii::$app->db->getTransaction();
            if (!$result->hasErrors()) {
                $transaction->commit();
            } else {
                $transaction->rollBack();
            }
        }
        return parent::afterAction($action, $result);
    }

    public function actions()
    {
        $actions = parent::actions();
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];
        return $actions;
    }

    public function prepareDataProvider()
    {
        $searchModel = new ModelsPacienteSearch();
        $dataProvider =  $searchModel->search(Yii::$app->request->queryParams);
        return $dataProvider;
    }
}
