<?php

namespace app\modules\Apiv1\controllers;

use yii\rest\ActiveController;
use app\models\ObrasocialSearch;
use app\models\PatologiaSearch;
use app\models\PacientepatologiaSearch;

use app\models\Usuario;
use app\modules\Apiv1\models\Paciente;
use app\models\PacienteSearch as ModelsPacienteSearch;
use app\modules\Apiv1\models\Patologia;
use app\modules\Apiv1\models\PacientePatologia;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataFilter;
use yii\data\ActiveDataProvider;
use yii\data\DataFilter;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

/**
 * Default controller for the `apiv1` module
 */
class MedicoController extends ActiveController
{
    public $modelClass = 'app\modules\Apiv1\models\Paciente';

    public function beforeAction($action)
    {
        if ($action->id == 'create') {
            Yii::$app->db->beginTransaction();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        if ($action->id == 'create') {
            $params = Yii::$app->getRequest()->getBodyParams();
            if (isset($params['patologia'])) {
                foreach ($params['patologia'] as $pat_id) {
                    $model = new Pacientepatologia(['[paciente_id' => $result->id, 'patologia_id' => $pat_id]);
                    if (!$model->save()) {
                        $result->addErrors($model->getErrors());
                    }
                }
            }
            $transaction = Yii::$app->db->getTransaction();
            if (!$result->hasErrors()) {
                $transaction->commit();
            } else {
                $transaction->rollBack();
            }
        }
        return parent::afterAction($action, $result);
    }

    public function actions()
    {
        $actions = parent::actions();
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];
        return $actions;
    }

    public function prepareDataProvider()
    {
        $searchModel = new ModelsPacienteSearch();
        $dataProvider =  $searchModel->search(Yii::$app->request->queryParams);
        return $dataProvider;
    }
<<<<<<< HEAD
}
=======
  
}





>>>>>>> cc9bbe6fee51c4d4a8f405083d584071763be1a8
